### PR TITLE
feat: Added scroll-to-top feature

### LINKED ISSUE #88: Add a scroll-to-top button on the website
I would like to add a new feature to the website, a scroll-to-top button that will take the user to the top of the page when clicked on. This comes quite handy when the user reaches the end of the page and has to scroll way back to the top.

### PR DESCRIPTION
**Pull request by m-code12**
### Issue Fix
Fixes #88 

**Description of changes made** 
Added a scroll-to-top feature.

**Submissions guide:**

- [ ] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [ ] Have you lint your code locally prior to submission?

**Screenshots (if applicable):**

Screenshot (302)

Screenshot (303)

Screenshot (304)

Screenshot (305)

### CODE REVIEW

**Review by s-ayush2903 — CHANGES_REQUESTED** [review]
Few nits:
* The back to top button coincides with the snackbar(in mobile version)
* Also, we can get this back to top functionality implemented for projects and archive page as well, it'll be better

**Comment by s-ayush2903** [comment]
Also, it'll look nicer if the button is perfectly circular.

**Comment by m-code12** [comment]
@s-ayush2903 I have made the requested changes.

**Comment by s-ayush2903** [comment]
I can see you've added the code that handles responsiveness, but I checked it and it doesn't seem to work as expected, I'm attaching the screenshot here. Did you check it after implementing the change?(I was talking about the button-snackbar protrusion)
|Have a look at snackbar at bottom|
|--|
|nigga|

**Comment by m-code12** [comment]
> I can see you've added the code that handles responsiveness, but I checked it and it doesn't seem to work as expected, I'm attaching the screenshot here. Did you check it after implementing the change?(I was talking about the button-snackbar protrusion)
> 
> Have a look at snackbar at bottom
> nigga

@s-ayush2903 Actually, I am not able to see the snackbar when I run the website locally. Even then, I have made the changes and hope it works perfectly.

**Comment by s-ayush2903** [comment]
Although the config looks hardcoded to me but we can merge it here. If you want to explore more then you can search for some attribute of the button so that it dodges the snackbar and changes it position dynamically i.e., appears few pixels above when snackbar is being displayed and then aligns itself to the bottom of the screen as soon as the snackbar is dismissed. Its your call now.

>  Actually, I am not able to see the snackbar when I run the website locally. Even then, I have made the changes and hope it works perfectly.

For this, I would say you should [sync your fork](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/syncing-a-fork) with the master branch of this repo, I can see your current branch is behind mainstream's master, this should fix the problem being faced by you

**Comment by m-code12** [comment]
> Although the config looks hardcoded to me but we can merge it here. If you want to explore more then you can search for some attribute of the button so that it dodges the snackbar and changes it position dynamically i.e., appears few pixels above when snackbar is being displayed and then aligns itself to the bottom of the screen as soon as the snackbar is dismissed. Its your call now.
> 
> > Actually, I am not able to see the snackbar when I run the website locally. Even then, I have made the changes and hope it works perfectly.
> 
> For this, I would say you should [sync your fork](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/syncing-a-fork) with the master branch of this repo, I can see your current branch is behind mainstream's master, this should fix the problem being faced by you

I did this, but still can't see the snack bar. If it is doing the work, maybe you can merge it.

**Comment by s-ayush2903** [comment]
Well this shouldn't happen you should be able to see it, can you create an issue that describes that snackbar isn't visible on your device and providing the device details(i.e., which mobile it is), so that we can fix it.

**Review by s-ayush2903 — APPROVED** [review]
LGTM

**Pull request merged**
