### PR TITLE
Archive Page using details and summary tag with some styling

### LINKED ISSUE #99: Archive Page using summary and details tag
**Is your feature request related to a problem? Please describe.**
Currently there is lot of scrolling on the archive page.

**Describe the solution you'd like**
What we can do is hide the projects until user search for specific year's project.

## Video

https://user-images.githubusercontent.com/59874304/103624612-c7f2d600-4f5f-11eb-8edc-3a46491c8ca3.mp4

**Additional context**
There is two things that I can do(if needed):
1. can show Previous Sponsors( means will remove summary tag)
2. further styling suggested by you !!

@s-ayush2903 @Ankit7Das do you like this ? if you like this so I can make a quick PR for this !!

### PR DESCRIPTION
**Pull request by Vishal-raj-1**
### Issue Fix
Fixes #99 

**Description of changes made** 
I am hiding projects for each year and will show the project iff user want to see the projects of particular year. I have adding some styling as well.
 
**Submissions guide:**

- [ ] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [ ] Have you lint your code locally prior to submission?

@s-ayush2903 @Ankit7Das Please review it !! 😄

### CODE REVIEW

**Comment by s-ayush2903** [comment]
@Vishal-raj-1 same comment as https://github.com/NJACKWinterOfCode/NJACKWinterOfCode.github.io/pull/102#pullrequestreview-561947921

**Comment by Vishal-raj-1** [comment]
@s-ayush2903 @Ankit7Das I have restore the indentation. Please review it !!

**Comment by Vishal-raj-1** [comment]
#102 will close this issues as well. so i am closing this PR as well.

**Comment by Vishal-raj-1** [comment]
@s-ayush2903 Bhaiya if I open this PR !! this will generate conflicts in other PR !! so I am just closing this PR !! and #102 will solve this issue as well.

**Pull request closed without merging**
