### PR TITLE
adding icons in contact page 

### LINKED ISSUE #92: showing icons instead of links
**Is your feature request related to a problem? Please describe.**
Clicking on links is not looks nice to me on contact page.

**Describe the solution you'd like**
 I would like to suggest have icons for facebook , twitter , github , gitter and mails.

contact

### PR DESCRIPTION
**Pull request by Vishal-raj-1**
### Issue Fix
Fixes #92 

**Description of changes made** 
 I have adding the icons which look nice both in desktop and mobile view. I have adding some hover effect as well. I have centralize the images. (check video for more info)

**Submissions guide:**

- [ ] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [ ] Have you lint your code locally prior to submission?

## Video

https://user-images.githubusercontent.com/59874304/103546374-e5c12c00-4ec8-11eb-9c81-fc4261a9096e.mp4

@s-ayush2903 @Ankit7Das Sir Please Review my PR !!

### CODE REVIEW

**Comment by s-ayush2903** [comment]
@Vishal-raj-1 This is not how it works, in order to open a PR you have to make sure that no one else is working on it and seek approval by maintainer to work on the issue, you never commented on the issue that you want to work on it and it was not good to assign you as neither had commented or mentioned anywhere in the issue about your interest in it moreover, one more participant was involved in the corresponding issue which displayed their interest/willingness to work on it. This isn't for this repo only, this is a rule of thumb in open source projects

**Comment by Vishal-raj-1** [comment]
I have open this issue for myself 🙃. Sorry I have forget to mentioned that
I am working on that !!

**Review by s-ayush2903 — CHANGES_REQUESTED** [review]
* You can definitely use better(and visible) icon for gitter, use gmail icon for gmail address and the normal mail icon for the webmail(the one with domain name `@iitp.ac.in`)

Also the current UX doesn't look pleasant to me, any thoughts do you have and I'm pinging here @Ankit7Das as well for input on the same, because those icons below pictures of organizers look a bit weird(because of their noticably large size)

**Comment by s-ayush2903** [comment]
Also @Vishal-raj-1 you needn't mark the work as _done_ unless you've done it in any commit, you should uncheck the appropriate checkboxes(in the PR description) : )

**Comment by Vishal-raj-1** [comment]
> * You can definitely use better(and visible) icon for gitter, use gmail icon for gmail address and the normal mail icon for the webmail(the one with domain name `@iitp.ac.in`)

ok sure !! 


> Also the current UX doesn't look pleasant to me, any thoughts do you have and I'm pinging here @Ankit7Das as well for input on the same, because those icons below pictures of organizers look a bit weird(because of their noticably large size)

So I can do one thing, will do text align left(like before) and decrease the font-size of facebook and github icons.

**Comment by Vishal-raj-1** [comment]
> Also @Vishal-raj-1 you needn't mark the work as _done_ unless you've done it in any commit, you should uncheck the appropriate checkboxes(in the PR description) : )

updated !!

**Comment by Vishal-raj-1** [comment]
@s-ayush2903 @Ankit7Das I have resolved the issues !! Please review it 🔥

**Comment by s-ayush2903** [comment]
The UI looks fine, good work :+1:
Now that I go through the files changed I can see the same indentation changes that ain't needed(review same as https://github.com/NJACKWinterOfCode/NJACKWinterOfCode.github.io/pull/102#pullrequestreview-561947921), we'll configure the repository for the contributions entirely via adding a global codestyle in the project which will allow people to format the file according to the lints configured in the repository(that'll be done as the program finishes and we get back on website to improve it for next edition), but for now you'll have to revert irrelevant changes on your own sorry for that

**Comment by Vishal-raj-1** [comment]
@s-ayush2903 @Ankit7Das I have restore the previous indentation. Please review it !! 🔥

**Comment by Vishal-raj-1** [comment]
#102 will solve this issue as well !! I am closing this PR.

**Comment by s-ayush2903** [comment]
@Vishal-raj-1 You were not supposed to close it, this is fine, we can merge it. I'm reopening it :+1:

**Review by s-ayush2903 — APPROVED** [review]
LGTM

**Comment by Vishal-raj-1** [comment]
> @Vishal-raj-1 You were not supposed to close it, this is fine, we can merge it. I'm reopening it 👍

Sir I have closing this PR !! Because what I have done is solving one issue and make one PR and solving another issue on another branch. But I am opening new branch after opening the PR !! from the next time I will open the branch first then do changes and make a PR from that branch and start working on another issue on another branch.

Let me clarify you what happen here !! 

This PR solve the issues of adding icons in contact page, #101 will solve this issue as well drop down list issues and #102 will solve this two issues and search bar.


sorry for the inconvenience. I was stuck in branching. I can do rebasing as well(fixup and squashing commits) but I feel there is no need to do that because it will deploy with the last commit that we have done on PR !!

**Comment by Vishal-raj-1** [comment]
> LGTM

Thank you for merging !! Feeling relaxed I was totally stuck because of that indentation.

**Pull request merged**
