### PR TITLE
adding search bar for project page, and dropdown list on archive page.

### LINKED ISSUE #91: add search bar for selection of projects
**Is your feature request related to a problem? Please describe.**
A search bar in project page will help participants to select project on the basis of their tech stack. 

**Describe the solution you'd like**
I will add a search bar at the top of projects. which will show projects on the basis of search terms.

### LINKED ISSUE #99: Archive Page using summary and details tag
**Is your feature request related to a problem? Please describe.**
Currently there is lot of scrolling on the archive page.

**Describe the solution you'd like**
What we can do is hide the projects until user search for specific year's project.

## Video

https://user-images.githubusercontent.com/59874304/103624612-c7f2d600-4f5f-11eb-8edc-3a46491c8ca3.mp4

**Additional context**
There is two things that I can do(if needed):
1. can show Previous Sponsors( means will remove summary tag)
2. further styling suggested by you !!

@s-ayush2903 @Ankit7Das do you like this ? if you like this so I can make a quick PR for this !!

### LINKED ISSUE #103: We Should remove student registration popup message.
**Describe the bug**
As NWOC 2020 ends so we can comment the code for this.

**To Reproduce**
1. Comment those code for now.

**Expected behavior**
As registration closes this should be shown on website as well

**Actual behavior**
It is shown registration are active.

**Screenshots**

notification

### PR DESCRIPTION
**Pull request by Vishal-raj-1**
**Description of changes made** 

- I have build a dropdown list of project in archive section and adding styling for the same which will fixes #99 .
- I have adding the search bar which will show only those project with have those tags. I am comparing repo-stats innerHTML with search value. I have adding some CSS on search bar and repo card(on hovering) which will fixes #91 .
- Commenting registration message for now fixes #103 .

**Submissions guide:**

- [ ] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [ ] Have you lint your code locally prior to submission?

@s-ayush2903 @Ankit7Das Please review it before NWOC ends !!

P.S: I have learn a lot while doing this !! 🔥

### CODE REVIEW

**Review by s-ayush2903 — CHANGES_REQUESTED** [review]
First of all, revert all the indentation changes and un-necessary whitespace/newline additions in the files. I can see you applied your local indentation on the projects which has resulted in sheer size of the PR, please revert changes like this to speed up the review process because even if we merge this(with un-necessary indentation changes), then other PRs will result in conflicts and then everyone will have to resolve it own their own, which in itself can prove to be a time consuming process

**Comment by Vishal-raj-1** [comment]
Ok 👌 Will send it you tomorrow 😊

**Comment by Vishal-raj-1** [comment]
@s-ayush2903 @Ankit7Das Please review it !! 🔥

**Comment by s-ayush2903** [comment]
@Vishal-raj-1 I can see you've messed up your commit history, I don't want to press this point to clean the history, but you should revert the changes in the file that ain't related to the subject of the issue which this PR targets, like for example, for this PR there should be no changes visible in `contact.html` & `archive.html` as this PR aims to implement search feature for _Projects_ section only, and also the changes made their are just order & indentation changes which is resulting in the sheer size of this PR, you should revert 'em, to be specific, for this PR changes should be visible in only `style.css` and `projects.html` files, I'm pretty sure this can be done quite easily. This problem is with all your current PRs, you should now revert the changes in files that ain't related to the issue subject(a time saving hack for it is to copy and paste the unrelated files from the mainstream and then push) and it should work fine 

Also you can maintain clean commit history by keeping your `master/dev` branch clean and regularly up to date with the main repo's active branch whenever you create a new commit/PR, create a new branch from your _clean_ branch, this'll ease stuff for you and reviewer as well.

**Comment by Vishal-raj-1** [comment]
let me do one thing, I am closing other two PR and solving three issues in one PR !!

**Comment by Vishal-raj-1** [comment]
> @Vishal-raj-1 I can see you've messed up your commit history, I don't want to press this point to clean the history, but you should revert the changes in the file that ain't related to the subject of the issue which this PR targets, like for example, for this PR there should be no changes visible in `contact.html` & `archive.html` as this PR aims to implement search feature for _Projects_ section only, and also the changes made their are just order & indentation changes which is resulting in the sheer size of this PR, you should revert 'em, to be specific, for this PR changes should be visible in only `style.css` and `projects.html` files, I'm pretty sure this can be done quite easily. This problem is with all your current PRs, you should now revert the changes in files that ain't related to the issue subject(a time saving hack for it is to copy and paste the unrelated files from the mainstream and then push) and it should work fine



**Description of changes made** 

- I have build a dropdown list of project in archive section and adding styling for the same which will fixes #99 .
- I have adding the search bar which will show only those project with have those tags. I am comparing repo-stats innerHTML with search value. I have adding some CSS on search bar and repo card(on hovering) which will fixes #91 .

@s-ayush2903 @Ankit7Das Please review it before NWOC ends !!

**Comment by Vishal-raj-1** [comment]
>(a time saving hack for it is to copy and paste the unrelated files from the mainstream and then push) and it should work fine

Let me try this as well !!

**Comment by Vishal-raj-1** [comment]
@s-ayush2903 @Ankit7Das Any update ? Now This PR solve two issues #99 and #91 .  For these issues we have to change in `archive.html` , `project.html `and `style.css` .

I have update PR message and title for the same !!

**Comment by s-ayush2903** [comment]
@Vishal-raj-1 This isn't how it works, I've told you multiple times that your PR unnecessarily large due formatting changes and I can still see 'em present here, in order to get it merged you'll have to fix this problem

**Comment by Vishal-raj-1** [comment]
> @Vishal-raj-1 This isn't how it works, I've told you multiple times that your PR unnecessarily large due formatting changes and I can still see 'em present here, in order to get it merged you'll have to fix this problem

oh formatting changes. I am doing it right away.

**Comment by Vishal-raj-1** [comment]
@s-ayush2903 @Ankit7Das Yep !! It's done now. I have understand my mistake. I have copied archive.html and project.html from master then copy the changes from this PR !! and it's work. Now it is acceptable.

**Comment by Vishal-raj-1** [comment]
for #103 . I am doing changes in this PR only as it is beginner level problem doesn't need to more PR for this. It fixes #103

**Comment by s-ayush2903** [comment]
Good job @Vishal-raj-1! Nice work

**Review by s-ayush2903 — APPROVED** [review]
LGTM

**Comment by Vishal-raj-1** [comment]
> Good job @Vishal-raj-1! Nice work

Thanks  Sir !!

**Pull request merged**
