### PR TITLE
feature enhancement: Improve Leaderboard (#59)

### LINKED ISSUE #59: improving the leaderboard
The current leaderboard looks like this.

image

I would like to improve upon this Leaderboard, and make it attractive.

### PR DESCRIPTION
**Pull request by tusharnankani**
Closes #59 

This is how the updated leaderboard will look like.

demo-leaderboard

Let me know if any more changes are to be made.

### CODE REVIEW

**Comment by s-ayush2903** [comment]
Nicee, this looks cool, let it be open. We'll get a review on it

**Review by s-ayush2903 — APPROVED** [review]
Nice work, lgtm

**Review by Ankit7Das — APPROVED** [review]

**Comment by s-ayush2903** [comment]
@tusharnankani This makes the leaderboard un-responsive, open the leaderboard on your mobile device, then observe it. Can you create an issue and push a fix.

**Comment by tusharnankani** [comment]
> Can you create an issue and push a fix.

Will do it right away 👍🏻

**Pull request merged**
